name: data-x
channels:
  - conda-forge
dependencies:
  - anaconda-client=1.6.14
  - anaconda-project=0.8.2
  - bokeh=0.13.0
  - cryptography=2.2.2
  - cython=0.28.3
  - dask=0.18.1
  - flask=1.0.2
  - gensim=3.4.0
  - hdf5=1.10.2
  - html5lib=0.9999999
  - jupyter=1.0.0
  - jupyterlab=0.32.1
  - keras=2.2.0
  - matplotlib=2.2.2
  - notebook=5.6.0
  - numba=0.39.0
  - numpy=1.14.5
  - opencv=3.4.1
  - pandas=0.23.3
  - pip=10.0.1
  - py-opencv=3.4.1
  - py-xgboost=0.72
  - python=3.6.6
  - requests=2.19.1
  - scikit-image=0.14.0
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - seaborn=0.8.1
  - spyder-kernels=0.2.4
  - sqlalchemy=1.2.8
  - sqlite=3.24.0
  - statsmodels=0.9.0
  - tensorboard=1.8.0
  - tensorflow=1.8.0
  - pip:
    - tables==3.4.4